name: Mac
on: [push]
jobs:
  pack:
    name: Build
    runs-on: macos-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.400'
      - name: Wasm Tools 
        run: dotnet workload install wasm-tools
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore
        run: dotnet paket restore
      - name: Build
        run: dotnet build -c Release