name: Windows
on: [push]
jobs:
  pack:
    name: Build
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Wasm Tools
        run: dotnet workload install wasm-tools
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore
        run: dotnet paket restore
      - name: Build
        shell: cmd
        run: dotnet build -c Release