name: Windows
on: [push]
jobs:
  pack:
    name: Build
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.401'
      - name: Wasm Tools
        run: dotnet workload install wasm-tools-net6
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore
        run: dotnet paket restore
      - name: Build
        shell: cmd
        run: dotnet build -c Release